// events
export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';

export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';

export const JOIN_EVENT_REQUEST = 'JOIN_EVENT_REQUEST';
export const JOIN_EVENT_SUCCESS = 'JOIN_EVENT_SUCCESS';
export const JOIN_EVENT_FAILURE = 'JOIN_EVENT_FAILURE';

export const LEAVE_EVENT_REQUEST = 'LEAVE_EVENT_REQUEST';
export const LEAVE_EVENT_SUCCESS = 'LEAVE_EVENT_SUCCESS';
export const LEAVE_EVENT_FAILURE = 'LEAVE_EVENT_FAILURE';

// router
export const NAVIGATE = 'NAVIGATE';
